# You can learn more about this file at https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file.
# This links to open source non-profits until such time as I have a reason to accept donations.

custom:
  - https://sfconservancy.org/
  - https://opensource.org/
