version: '3'

vars:
  PY: "{{.PYTHON | default `python`}}"
  GIT_REMOTE: "git@github.com:nicholasgrose/project_template.git"

tasks:
  bootstrap:
    desc: Bootstrap the repository
    deps:
      - git:bootstrap
      - docs:bootstrap
      - cli:bootstrap

  git:bootstrap:
    desc: Bootstrap git repo
    status:
      - git status
    cmds:
      - git init
      - git add -A
      - git commit -m "Initial commit"
      - git branch -M main
      - "git remote add origin {.GIT_REMOTE}"
      - git push -u origin main

  docs:bootstrap:
    desc: Create/update MkDocs virtualenv and install deps
    status:
      - test -d docs/.venv
    cmd: "{{.PY}} -m scripts.docs.mkdocs_bootstrap"

  docs:serve:
    desc: Serve docs locally with live reload
    deps: [ docs:bootstrap ]
    cmd: "{{.PY}} -m scripts.docs.mkdocs serve"

  cli:bootstrap:
    desc: Create/update CLI virtualenv and install deps
    status:
      - test -d generation_cli/.venv
    cmd: "{{.PY}} -m scripts.generation_cli.venv_bootstrap"

  root:bootstrap:
    desc: Bootstrap the scripts of the overall repository
    status:
      - test -d .venv
    cmd: "{{.PY}} -m scripts.root.venv_bootstrap"
