pages:
  stage: deploy
  image: python:latest
  script:
    - cd docs
    - pip install -r requirements.txt
    - mkdocs build --site-dir ../public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.cache/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
