# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Nicholas's Project Template
repo_name: nicholasgrose/project_template
repo_url: https://github.com/nicholasgrose/project_template
site_url: ""
use_directory_urls: false
site_author: Nicholas Rose
nav:
  - Home: index.md
  - Usage: usage.md
docs_dir: content
theme:
  name: material
  features:
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep orange
      accent: indigo
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: deep orange
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class:
        - pymdownx.inlinehilite
        - pymdownx.snippets
        - pymdownx.superfences
